[package]
name = "Homework3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vector"
path = "src/vector.rs"

[[bin]]
name = "hash"
path = "src/hash.rs"

[dependencies]
